<?php

namespace App\Services;

use App\Models\Site;
use Illuminate\Support\Facades\File;

class NginxService
{
    protected string $sitesAvailablePath = '/etc/nginx/sites-available';
    protected string $sitesEnabledPath = '/etc/nginx/sites-enabled';

    public function __construct()
    {
        // If not in Linux root environment, use a storage fallback path for safe testing & inspection
        if (PHP_OS_FAMILY !== 'Linux' || !is_dir($this->sitesAvailablePath)) {
            $this->sitesAvailablePath = storage_path('app/nginx/sites-available');
            $this->sitesEnabledPath = storage_path('app/nginx/sites-enabled');
            File::ensureDirectoryExists($this->sitesAvailablePath);
            File::ensureDirectoryExists($this->sitesEnabledPath);
        }
    }

    /**
     * Generate the complete Nginx virtual host configuration string.
     */
    public function generateConfig(Site $site): string
    {
        $domain = $site->domain;
        $aliases = $site->aliases ? ' ' . trim($site->aliases) : '';
        $serverNames = $domain . $aliases;
        $root = rtrim($site->root_path, '/') . ($site->web_directory ? '/' . ltrim($site->web_directory, '/') : '');
        $phpVersion = $site->php_version ?: '8.3';
        $port = $site->port ?: 3000;

        if ($site->ssl_enabled) {
            return $this->generateSslConfig($site, $serverNames, $root, $phpVersion, $port);
        }

        return $this->generateHttpConfig($site, $serverNames, $root, $phpVersion, $port);
    }

    private function generateHttpConfig(Site $site, string $serverNames, string $root, string $phpVersion, int $port): string
    {
        $typeConfig = match ($site->type) {
            'nextjs' => $this->getNextJsBlock($port),
            'laravel' => $this->getLaravelBlock($root, $phpVersion),
            'wordpress' => $this->getWordPressBlock($root, $phpVersion),
            default => $this->getPhpBlock($root, $phpVersion),
        };

        return <<<NGINX
# Auto-generated by VPS Panel for {$site->domain} ({$site->type})
server {
    listen 80;
    listen [::]:80;
    server_name {$serverNames};

    access_log /var/log/nginx/{$site->domain}.access.log;
    error_log /var/log/nginx/{$site->domain}.error.log warn;

{$typeConfig}

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Deny access to hidden files
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
NGINX;
    }

    private function generateSslConfig(Site $site, string $serverNames, string $root, string $phpVersion, int $port): string
    {
        $typeConfig = match ($site->type) {
            'nextjs' => $this->getNextJsBlock($port),
            'laravel' => $this->getLaravelBlock($root, $phpVersion),
            'wordpress' => $this->getWordPressBlock($root, $phpVersion),
            default => $this->getPhpBlock($root, $phpVersion),
        };

        $sslCert = "/etc/letsencrypt/live/{$site->domain}/fullchain.pem";
        $sslKey = "/etc/letsencrypt/live/{$site->domain}/privkey.pem";

        return <<<NGINX
# Auto-generated by VPS Panel for {$site->domain} ({$site->type}) - HTTPS Enabled
server {
    listen 80;
    listen [::]:80;
    server_name {$serverNames};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {$serverNames};

    ssl_certificate {$sslCert};
    ssl_certificate_key {$sslKey};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    access_log /var/log/nginx/{$site->domain}.access.log;
    error_log /var/log/nginx/{$site->domain}.error.log warn;

{$typeConfig}

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Deny access to hidden files
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
NGINX;
    }

    private function getNextJsBlock(int $port): string
    {
        return <<<NGINX
    location / {
        proxy_pass http://127.0.0.1:{$port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /_next/static {
        proxy_pass http://127.0.0.1:{$port};
        proxy_cache_bypass \$http_upgrade;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
NGINX;
    }

    private function getLaravelBlock(string $root, string $phpVersion): string
    {
        return <<<NGINX
    root {$root};
    index index.php index.html;

    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php{$phpVersion}-fpm.sock;
        fastcgi_param SCRIPT_FILENAME \$realpath_root\$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
NGINX;
    }

    private function getWordPressBlock(string $root, string $phpVersion): string
    {
        return <<<NGINX
    root {$root};
    index index.php index.html;

    location / {
        try_files \$uri \$uri/ /index.php?\$args;
    }

    # Disallow PHP execution in uploads directory (WordPress Security)
    location ~* /(?:uploads|files)/.*\.php$ {
        deny all;
    }

    # Block access to xmlrpc.php against brute-force attacks
    location = /xmlrpc.php {
        deny all;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php{$phpVersion}-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires max;
        log_not_found off;
    }
NGINX;
    }

    private function getPhpBlock(string $root, string $phpVersion): string
    {
        return <<<NGINX
    root {$root};
    index index.php index.html index.htm;

    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php{$phpVersion}-fpm.sock;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }
NGINX;
    }

    /**
     * Write config file, link to sites-enabled, test & reload Nginx.
     */
    public function deployVhost(Site $site): array
    {
        $configContent = $this->generateConfig($site);
        $vhostFile = "{$this->sitesAvailablePath}/{$site->domain}.conf";
        $enabledSymlink = "{$this->sitesEnabledPath}/{$site->domain}.conf";

        File::put($vhostFile, $configContent);

        if (!file_exists($enabledSymlink)) {
            @symlink($vhostFile, $enabledSymlink);
        }

        return $this->testAndReload();
    }

    public function testAndReload(): array
    {
        if (PHP_OS_FAMILY === 'Linux') {
            $testOutput = @shell_exec('nginx -t 2>&1');
            if (str_contains((string) $testOutput, 'successful')) {
                @shell_exec('systemctl reload nginx 2>&1');
                return ['success' => true, 'message' => 'Nginx reloaded successfully.'];
            }
            return ['success' => false, 'message' => 'Nginx test failed: ' . $testOutput];
        }

        return ['success' => true, 'message' => 'Virtual host configuration written (Dev Mode).'];
    }

    public function removeVhost(Site $site): void
    {
        $vhostFile = "{$this->sitesAvailablePath}/{$site->domain}.conf";
        $enabledSymlink = "{$this->sitesEnabledPath}/{$site->domain}.conf";

        if (file_exists($enabledSymlink)) @unlink($enabledSymlink);
        if (file_exists($vhostFile)) @unlink($vhostFile);

        $this->testAndReload();
    }
}
